# ---- build ----
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# ---- runtime ----
FROM node:20-alpine

WORKDIR /app

# Copier le build
COPY --from=build /app/.output ./.output
COPY package*.json ./

# Installer les dépendances de production (pour preview)
RUN npm install --production

EXPOSE 3000

# Lancer Nuxt preview via npx pour être sûr que Nuxt soit trouvé
CMD ["npx", "nuxt", "preview"]
