FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
    git unzip libicu-dev libzip-dev \
    && docker-php-ext-install intl pdo pdo_mysql zip

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# 🔥 CRUCIAL — créer les dossiers attendus par Symfony
RUN mkdir -p var/cache var/log public/uploads/images public/assets \
    && chmod -R 777 var public

RUN sed -i 's|^listen = .*|listen = 0.0.0.0:9000|' /usr/local/etc/php-fpm.d/www.conf

CMD ["php-fpm"]
