# =========================
# FRONTEND - Nuxt
# =========================
server {
    listen 80;
    server_name ton-domaine.local;

    location / {
        proxy_pass http://frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# =========================
# API - Symfony / API Platform
# =========================
server {
    listen 80;
    server_name api.ton-domaine.local nginx;

    root /var/www/html/public;
    index index.php;

    # Traiter les fichiers existants et sinon passer à index.php
    location / {
        try_files $uri /index.php$is_args$args;
    }

    # Fichiers PHP - uniquement index.php
    location ~ ^/index\.php(/|$) {
        fastcgi_pass backend:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS off;

    }

    # Interdire l'accès direct aux autres fichiers PHP
    location ~ \.php$ {
        return 404;
    }

    # Assets générés par AssetMapper
    location /assets/ {
        alias /var/www/html/public/assets/;
        access_log off;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Dossier uploads
    location /uploads/ {
        alias /var/www/html/public/uploads/;
        access_log off;
        expires 30d;
    }

    # Dossier bundles (API Platform / Swagger / fonts / JS / CSS)
    location /bundles/ {
        alias /var/www/html/public/bundles/;
        access_log off;
        expires 7d;
    }

    # Cache headers pour CSS / JS / images
    location ~* \.(?:css|js|gif|jpe?g|png|svg|woff2?|ttf|eot)$ {
        access_log off;
        expires 7d;
        add_header Cache-Control "public";
    }
}
