# config/api_resources/Product.yaml

App\Entity\ShippingMethod:
    operations:
        - class: ApiPlatform\Metadata\GetCollection
          
        - class: ApiPlatform\Metadata\Get
          
        - class: ApiPlatform\Metadata\Delete
          security: "is_granted('ROLE_ADMIN')"
        - class: ApiPlatform\Metadata\Post
          name: 'create_shipping_method'
          uriTemplate: '/shipping_methods/create'
          controller: App\Controller\ShippingMethod\CreateShippingMethodController
        - class: ApiPlatform\Metadata\Post
          name: 'update_shipping_method'
          uriTemplate: '/shipping_methods/{id}/update'
          controller: App\Controller\ShippingMethod\UpdateShippingMethodController
        - class: ApiPlatform\Metadata\Delete
          name: 'delete_product'
          uriTemplate: '/shipping_methods/{id}/delete'
          controller: App\Controller\ShippingMethod\SoftDeleteShippingMethodController